version: "3.8"
services:
  xaosao-admin:
    build:
      context: .
    restart: always
    networks:
      - xaosao-share-network
    env_file:
      - .env
    environment:
      - REMIX_DEV_ORIGIN=http://localhost:5173
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "5173:3000"
    volumes:
      # Only mount for dev — in prod you don’t want to overwrite built files
      - ./public:/app/public
networks:
  xaosao-share-network:
    external: false
