services:
  xaosao-admin:
    build:
      context: .
    restart: always
    networks:
      - xaosao-share-network
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "5173:3000"
networks:
  xaosao-share-network:
    external: false
